"""empty message

Revision ID: 53c4d1e4f1e8
Revises: b3b71da28672
Create Date: 2017-04-09 02:02:44.593712

"""

# revision identifiers, used by Alembic.
revision = '53c4d1e4f1e8'
down_revision = 'b3b71da28672'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
