"""empty message

Revision ID: 9d2a2fdeff6e
Revises: da11d366c286
Create Date: 2017-04-09 01:44:08.065402

"""

# revision identifiers, used by Alembic.
revision = '9d2a2fdeff6e'
down_revision = 'da11d366c286'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
