"""empty message

Revision ID: b3b71da28672
Revises: 9d2a2fdeff6e
Create Date: 2017-04-09 01:50:52.009076

"""

# revision identifiers, used by Alembic.
revision = 'b3b71da28672'
down_revision = '9d2a2fdeff6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
