"""empty message

Revision ID: da11d366c286
Revises: d51b6d50a14d
Create Date: 2017-04-08 01:58:41.760054

"""

# revision identifiers, used by Alembic.
revision = 'da11d366c286'
down_revision = 'd51b6d50a14d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
